### ISSUE TITLE
Improve some time-consuming loops

### ISSUE THREAD

**Issue by JinpengLI** [neurospin/pylearn-epac#5]
In splitters.py, when I set the number of permutation to **_1000**_ (not too big), it will take 5 minutes to do the memory allocation, **deepcopy(task)** :

``` python
class ParPerm(WFNodeSplitter):
    def __init__(self, task, n_perms, permute="y", random_state=None,
                 reducer=None, **kwargs):
.....
        for perm in self.children:
            task = copy.deepcopy(task)
            task = task if isinstance(task, WFNode) else WFNodeEstimator(task)
            perm.add_child(task)
....
```

Do you have some ideas to improve it ?

**Comment by DimitriPapadopoulos** [comment]
Jinpeng,

Which part of the code is slow? copy.deepcopy(), split.add_child() or both?

How large an objetc is "task"? I'm asking because:
    The most important one is a malloc implementation called
    pymalloc, designed specifically to handle large numbers of
    small allocations. Any object that is smaller than 256 bytes
    uses this allocator, while anything larger uses the system's
    malloc.
    http://www.evanjones.ca/python-memory.html

Le 29/04/2013 12:44, JinpengLI a écrit :

> In splitters.py, when I set the number of permutation to _/1000/_ (not
> too big), it will take 5 minutes to do the memory allocation,
> _deepcopy(task)_ :
> 
> class  ParCV(WFNodeSplitter):
>      def  **init**(self,  task,  n_folds,  random_state=None,  reducer=None,
>                   **kwargs):
> .....
> line  75:         for  split  in  self.children:
> line  76:             task  =  copy.deepcopy(task)
> line  77:             task  =  task  if  isinstance(task,  WFNode)  else  WFNodeEstimator(task)
> line  78:             split.add_child(task)
> ....
> 
> Do you have some ideas to improve it ? I fail to find a function to
> allocate all the tasks once. For example in c++, std::vector:resize(size).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurospin/pylearn-epac/issues/5.

## 

Dimitri Papadopoulos
CEA/Saclay
I2BM, NeuroSpin
91191 Gif-sur-Yvette cedex, France
+33 (0)1 69 08 79 12

**Comment by DimitriPapadopoulos** [comment]
Also it's not clear why you need deepcopy() which is indeed known to be 
very slow because it tries to detect pathological cases such as 
recursive objects.
Could you maybe avoid deepcopy() or optimize it by defining a more 
simple **deepcopy**()?

## 

Dimitri Papadopoulos
CEA/Saclay
I2BM, NeuroSpin
91191 Gif-sur-Yvette cedex, France
+33 (0)1 69 08 79 12

**Comment by DimitriPapadopoulos** [comment]
See:
http://writeonly.wordpress.com/2009/05/07/deepcopy-is-a-pig-for-simple-data/

Le 29/04/2013 12:44, JinpengLI a écrit :

> In splitters.py, when I set the number of permutation to _/1000/_ (not
> too big), it will take 5 minutes to do the memory allocation,
> _deepcopy(task)_ :
> 
> class  ParCV(WFNodeSplitter):
>      def  **init**(self,  task,  n_folds,  random_state=None,  reducer=None,
>                   **kwargs):
> .....
> line  75:         for  split  in  self.children:
> line  76:             task  =  copy.deepcopy(task)
> line  77:             task  =  task  if  isinstance(task,  WFNode)  else  WFNodeEstimator(task)
> line  78:             split.add_child(task)
> ....
> 
> Do you have some ideas to improve it ? I fail to find a function to
> allocate all the tasks once. For example in c++, std::vector:resize(size).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurospin/pylearn-epac/issues/5.

## 

Dimitri Papadopoulos
CEA/Saclay
I2BM, NeuroSpin
91191 Gif-sur-Yvette cedex, France
+33 (0)1 69 08 79 12

**Comment by JinpengLI** [comment]
To @DimitriPapadopoulos : "copy.deepcopy(task)" is very time-consuming. When I remove it, the loop run very fast. I am thinking can I remove it. @duchesnay

**Comment by duchesnay** [comment]
The problem was:
task = copy.deepcopy(task)
Followed by
perm.add_child(task)

Indeed task has self as parent, so the next deepcopy, will copy the parent, and then the whole tree. The bigger the tree is becoming the slower is the deepcopy.

The issue is solved by using:
node_cp = copy.deepcopy(node)
...
perm.add_child(node_cp)

The node has no parent, so deepcopy do not copy the whole tree
