### ISSUE TITLE
PERF: avoid subtree copying

### ISSUE THREAD

**Issue by duchesnay** [neurospin/pylearn-epac#7]
Objectives: reduce memory footprint, disk storage space.

Proposition:
subtrees (at least for ParCV and ParPerm) are not copied any more. Only one path from root to leave (except for ParMethods and ParGrid) is built.

To do:
- avoid storage of information. What is stored actually ?
  - Indices of re-slicing => re-compute it during transform
  - results => store them in a global key-indexed dict
  - Some minor key info =>  re-compute it while iterating over children
- dynamically move the same subtree from child to child when iterating over children.

**Comment by JinpengLI** [comment]
I propose an idea that you may be interested in. Instead of using data processing tree, we can use processing **_TABLE**_. As the figure below shown, the table only need linear size of memory space in terms of the number of different processes. 

![screenshot from 2013-05-14 22 50 50](https://f.cloud.github.com/assets/3331085/503881/fb5db6ea-bcd7-11e2-9b2f-9ace94588b20.png)

A job is represented by a **_NUMBER**_ which is composed of n digits (the depth of tree). For instance, the red rectangles show a data workflow using the number "0100". 

![screenshot from 2013-05-14 23 09 03](https://f.cloud.github.com/assets/3331085/503958/871604f6-bcda-11e2-8108-290808fcd6f5.png)

We can define a range of jobs by two numbers (starting and ending):

![screenshot from 2013-05-14 23 13 56](https://f.cloud.github.com/assets/3331085/503993/38613c1c-bcdb-11e2-9688-f355ef782c7a.png)

To process a range of jobs, we can increase the job number by one:

![screenshot from 2013-05-14 23 15 16](https://f.cloud.github.com/assets/3331085/504001/6bb68842-bcdb-11e2-9fad-63f95f8f12ce.png)

Between two successive jobs, some results could be reused:

![screenshot from 2013-05-14 23 16 31](https://f.cloud.github.com/assets/3331085/504009/92bc98c8-bcdb-11e2-9ca2-6b402e3b70ff.png)

At the end, since we use number for jobs, it easy to divide all jobs into n equal sets according to the number of processors.
